import { addDoc, collection, doc, getDocs, onSnapshot, setDoc } from 'firebase/firestore'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { db } from '../utils/firebaseConfig'

const Coins = collection(db, 'coins')

export default function Home() {
  const [coins, setCoins] = useState([])
  
  useEffect(() => {
    onSnapshot(Coins,
      snapshot => setCoins(snapshot.docs.map(item => ({ ...item.data(), id: item.id }))),
      err => console.error(err)
    )
  }, [])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <button onClick={addADA}>Add ADA</button>
        
        <div>
          {coins.map(coin => (
            <div>
              {coin.id} - {coin.price}
            </div>
          ))}
        </div>

      </main>
    </div>
  )

  async function addADA() {
    await setDoc(doc(db, 'coins', 'ADA'), {
      price: 12.599
    })
  }
}
